// Data produk Martabak Manja.
// Ganti field `img` dengan path foto asli di assets/img/ kapan pun sudah tersedia.

const bestSellerProducts = [
  {
    id: 'bs-1',
    name: 'Martabak Manis Cokelat Keju',
    desc: 'Adonan tebal lumer, ditaburi cokelat meses premium dan keju parut melimpah.',
    price: 45000,
    img: 'assets/img/produk1.jpg',
    category: 'Martabak Manis',
    badge: 'Best Seller',
  },
  {
    id: 'bs-2',
    name: 'Martabak Manis Kacang Original',
    desc: 'Resep klasik dengan taburan kacang tanah sangrai dan siraman margarin susu.',
    price: 38000,
    img: 'assets/img/produk2.jpg',
    category: 'Martabak Manis',
    badge: 'Best Seller',
  },
  {
    id: 'bs-3',
    name: 'Martabak Manis Green Tea',
    desc: 'Perpaduan pahit lembut green tea Jepang dengan manisnya susu kental.',
    price: 42000,
    img: 'assets/img/produk3.jpg',
    category: 'Martabak Manis',
    badge: 'Best Seller',
  },
  {
    id: 'bs-4',
    name: 'Martabak Manis Nutella Almond',
    desc: 'Olesan Nutella tebal dengan taburan almond panggang yang renyah.',
    price: 52000,
    img: 'assets/img/produk4.jpg',
    category: 'Martabak Manis',
    badge: 'Best Seller',
  },
  {
    id: 'bs-5',
    name: 'Martabak Manis Tiramisu',
    desc: 'Sentuhan kopi espresso dan krim mascarpone ala dessert Italia.',
    price: 50000,
    img: 'assets/img/produk5.jpg',
    category: 'Martabak Manis',
    badge: 'Best Seller',
  },
  {
    id: 'bs-6',
    name: 'Martabak Manis Durian',
    desc: 'Durian montong asli dipadu krim manis, untuk pecinta durian sejati.',
    price: 55000,
    img: 'assets/img/produk6.jpg',
    category: 'Martabak Manis',
    badge: 'Best Seller',
  },
]

const unggulanProducts = [
  {
    id: 'ug-1',
    name: 'Martabak Telor Spesial Daging',
    desc: 'Isian daging sapi cincang bumbu rempah, telur bebek, dan daun bawang segar.',
    price: 35000,
    img: 'assets/img/produk7.jpg',
    category: 'Martabak Telor',
    badge: 'Unggulan',
  },
  {
    id: 'ug-2',
    name: 'Martabak Telor Ayam Suwir',
    desc: 'Ayam suwir gurih berbumbu kari ringan, dibungkus kulit tipis renyah.',
    price: 30000,
    img: 'assets/img/produk8.jpg',
    category: 'Martabak Telor',
    badge: 'Unggulan',
  },
  {
    id: 'ug-3',
    name: 'Martabak Telor Jumbo Komplit',
    desc: 'Ukuran jumbo dengan campuran daging, telur, dan sayuran lengkap.',
    price: 48000,
    img: 'assets/img/produk9.jpg',
    category: 'Martabak Telor',
    badge: 'Unggulan',
  },
  {
    id: 'ug-4',
    name: 'Martabak Telor Sapi Lada Hitam',
    desc: 'Cita rasa pedas gurih lada hitam yang menempel di setiap suapan.',
    price: 37000,
    img: 'assets/img/produk10.jpg',
    category: 'Martabak Telor',
    badge: 'Unggulan',
  },
  {
    id: 'ug-5',
    name: 'Martabak Telor Seafood',
    desc: 'Udang dan cumi segar berpadu dengan telur dan bumbu rempah pilihan.',
    price: 44000,
    img: 'assets/img/produk11.jpg',
    category: 'Martabak Telor',
    badge: 'Unggulan',
  },
  {
    id: 'ug-6',
    name: 'Martabak Telor Mini Original',
    desc: 'Ukuran mini pas untuk camilan, tetap gurih dan renyah di setiap gigitan.',
    price: 22000,
    img: 'assets/img/produk12.jpg',
    category: 'Martabak Telor',
    badge: 'Unggulan',
  },
]
